import { ResultCategory } from '../types/prompt';

export interface PromptTemplate {
  id: string;
  category: ResultCategory;
  title: string;
  resultType: string;
  targetAi: string;
  starterTopic: string;
  description: string;
}

export const TEMPLATES: PromptTemplate[] = [
  // 1. 문서 / 텍스트 (Document)
  {
    id: 'doc-report',
    category: 'document',
    title: '경영진 업무 보고서',
    resultType: '업무 보고서',
    targetAi: 'chatgpt',
    starterTopic: '신규 서비스 런칭 후 1개월간의 주요 성과, 핵심 KPI 달성 현황 및 향후 개선 과제를 정리한 경영진 보고서',
    description: '핵심 지표와 실행 과제를 명확한 마크다운 구조로 요약 보고',
  },
  {
    id: 'doc-proposal',
    category: 'document',
    title: '신규 프로젝트 기획서',
    resultType: '기획서 / 제안서',
    targetAi: 'claude',
    starterTopic: '사내 업무 효율화를 위한 생성형 AI 도입 배경, 세부 실행 로드맵 및 예상 기대효과 기획서',
    description: '논리적인 배경 설명과 단계별 추진 일정을 담은 상세 기획서',
  },
  {
    id: 'doc-email',
    category: 'document',
    title: '프로모션 마케팅 이메일',
    resultType: '마케팅 카피 / 광고 문구',
    targetAi: 'chatgpt',
    starterTopic: '기존 가입 고객을 대상으로 프리미엄 기능 무료 체험을 제안하고 클릭을 유도하는 설득력 있는 뉴스레터 이메일',
    description: '매력적인 헤드라인과 행동 유도(CTA) 중심의 카피라이팅',
  },
  {
    id: 'doc-blog',
    category: 'document',
    title: '전문 기술 블로그 포스팅',
    resultType: '블로그 글',
    targetAi: 'chatgpt',
    starterTopic: '초보자를 위해 최신 IT 기술 개념을 일상적인 비유와 풍부한 예시로 알기 쉽게 설명하는 전문 기술 블로그 글',
    description: '독자의 이해도를 높이는 친절한 설명과 구조화된 소제목 구성',
  },

  // 2. 이미지 / 디자인 (Image)
  {
    id: 'img-product',
    category: 'image',
    title: '제품 광고 실사 샷',
    resultType: '실사 제품 사진 (Product Shot)',
    targetAi: 'midjourney',
    starterTopic: '자연광이 은은하게 들어오는 미니멀한 스튜디오에서 촬영된 고급 세라믹 텀블러 실사 제품 샷, 섬세한 질감과 부드러운 그림자',
    description: '스튜디오 조명, 카메라 렌즈, 텍스처를 강조한 실사 상업 사진',
  },
  {
    id: 'img-sns-ad',
    category: 'image',
    title: 'SNS 피드 광고 그래픽',
    resultType: '디지털 일러스트레이션',
    targetAi: 'midjourney',
    starterTopic: '2030 세대를 타깃으로 한 트렌디하고 활기찬 분위기의 인스타그램 피드용 프로모션 그래픽 아트',
    description: '시선을 끄는 색감과 현대적 그래픽 감각을 갖춘 소셜 미디어 비주얼',
  },
  {
    id: 'img-thumbnail',
    category: 'image',
    title: '유튜브 클릭 유도 썸네일',
    resultType: '유튜브 썸네일 그래픽',
    targetAi: 'auto',
    starterTopic: '시선을 사로잡는 선명한 색감과 고대비의 인물 표정이 돋보이는 흥미진진한 유튜브 썸네일 디자인',
    description: '작은 화면에서도 눈에 확 띄는 구도와 높은 클릭률 중심 설계',
  },
  {
    id: 'img-character',
    category: 'image',
    title: '3D 마스코트 캐릭터 콘셉트',
    resultType: '3D 캐릭터 콘셉트 아트',
    targetAi: 'midjourney',
    starterTopic: '친근하고 따뜻한 느낌의 픽사 3D 애니메이션 스타일 귀여운 동물 마스코트 캐릭터 콘셉트 아트',
    description: '부드러운 조명과 볼륨감 넘치는 3D 렌더링 스타일 캐릭터',
  },

  // 3. 프레젠테이션 (Presentation)
  {
    id: 'pres-pitchdeck',
    category: 'presentation',
    title: '스타트업 투자 피치덱',
    resultType: '스타트업 피치덱 (10-12장)',
    targetAi: 'chatgpt',
    starterTopic: '시리즈 A 투자 유치를 위한 비즈니스 모델, 문제 정의, 솔루션, 트랙션 및 자금 사용 계획 중심의 10장 피치덱 구성',
    description: 'VC 심사역의 관점에서 슬라이드별 핵심 메시지와 데이터 포인트 설계',
  },
  {
    id: 'pres-proposal',
    category: 'presentation',
    title: '경영진 보고용 기획 발표 슬라이드',
    resultType: '신규 프로젝트 제안 슬라이드',
    targetAi: 'claude',
    starterTopic: '신규 사업 아이템의 시장 기회와 타당성을 경영진에게 브리핑하기 위한 7장 핵심 제안 발표자료',
    description: '명확한 논리 전개와 의사결정 포인트를 짚어주는 슬라이드 구조',
  },
  {
    id: 'pres-workshop',
    category: 'presentation',
    title: '사내 교육 / 워크숍 강의자료',
    resultType: '교육 / 사내 워크숍 강의자료',
    targetAi: 'auto',
    starterTopic: '실무자들을 대상으로 생성형 AI 활용법과 실무 프롬프트 작성 팁을 전달하는 인터랙티브 워크숍 슬라이드',
    description: '청중의 참여를 유도하는 단계별 실습과 핵심 요점 정리',
  },
  {
    id: 'pres-quarterly',
    category: 'presentation',
    title: '분기 실적 성과 보고',
    resultType: '분기 실적 성과 보고 발표',
    targetAi: 'chatgpt',
    starterTopic: '분기별 매출 및 사용자 성장 지표를 시각화하여 공유하고 다음 분기 전략 과제를 제시하는 성과 발표 슬라이드',
    description: '차트 지표와 비즈니스 인사이트 중심의 발표 슬라이드',
  },

  // 4. 비디오 / 영상 (Video)
  {
    id: 'vid-product-ad',
    category: 'video',
    title: '신제품 홍보 광고 영상',
    resultType: '제품 홍보 광고 영상',
    targetAi: 'veo',
    starterTopic: '고급스러운 테이블 위에서 신제품 스마트워치의 세련된 마감과 인터페이스를 부드러운 카메라 무빙으로 담아내는 15초 광고 영상',
    description: '카메라 움직임, 얕은 심도, 잔잔한 조명과 앰비언트 사운드 묘사',
  },
  {
    id: 'vid-shorts',
    category: 'video',
    title: '바이럴 숏폼 / 릴스 영상',
    resultType: '유튜브 쇼츠 / 인스타 릴스 (15~30초)',
    targetAi: 'higgsfield',
    starterTopic: '첫 3초에 시선을 사로잡는 역동적인 인물 액션과 감각적인 화면 전환이 돋보이는 15초 세로형 릴스 영상',
    description: '빠른 속도감과 캐릭터 모션, 역동적인 카메라 연출 중심',
  },
  {
    id: 'vid-cinematic',
    category: 'video',
    title: '시네마틱 무비 트레일러',
    resultType: '시네마틱 무비 트레일러',
    targetAi: 'sora',
    starterTopic: '안개 자욱한 사이버펑크 도시의 밤거리에서 미래형 차량이 질주하는 연속 FPV 드론 궤적과 비에 젖은 네온 불빛 영상',
    description: '시간적/공간적 연속성과 사실적인 물리 반응, 빛 반사 연출',
  },
  {
    id: 'vid-flow-intro',
    category: 'video',
    title: '단계별 제품 소개 스토리보드 영상',
    resultType: '제품 홍보 광고 영상',
    targetAi: 'google_flow',
    starterTopic: '제품의 핵심 기능과 차별점을 도입-본론-결론의 순차적인 장면 전개와 시각 효과로 명확히 설명하는 30초 소개 영상',
    description: '스토리보드 씬 구분과 화면 전환, 내레이션 흐름을 고려한 영상 기획',
  },

  // 5. 오디오 / 보이스 (Audio)
  {
    id: 'aud-narration',
    category: 'audio',
    title: '내레이션 음성 안내',
    resultType: '광고 / 오디오북 내레이션',
    targetAi: 'elevenlabs',
    starterTopic: '신뢰감 있고 차분하며 따뜻한 중저음 톤으로 브랜드 스토리를 전달하는 다큐멘터리 스타일 음성 내레이션',
    description: '성우의 발화 톤, 감정, 호흡 조절과 음색 특화 지침',
  },
  {
    id: 'aud-podcast',
    category: 'audio',
    title: '팟캐스트 인트로 오프닝',
    resultType: '팟캐스트 인트로 / 징글',
    targetAi: 'elevenlabs',
    starterTopic: '경쾌하고 에너지 넘치는 분위기로 청취자의 호기심을 자극하는 테크 토크 팟캐스트 오프닝 멘트',
    description: '생동감 넘치는 억양과 명확한 딕션의 오프닝 멘트',
  },
  {
    id: 'aud-bgm',
    category: 'audio',
    title: '잔잔한 로파이 배경음악 (BGM)',
    resultType: '배경음악 (BGM) 생성',
    targetAi: 'suno',
    starterTopic: '집중과 힐링에 어울리는 잔잔하고 편안한 로파이(Lo-Fi) 칠합 비트와 따뜻한 어쿠스틱 피아노 멜로디',
    description: 'BPM, 악기 편성, 공간감 있는 사운드 텍스처 구성',
  },
  {
    id: 'aud-song',
    category: 'audio',
    title: '청량한 신스팝 보컬 곡',
    resultType: '완전한 곡 작곡 / 작사 (Suno/Udio)',
    targetAi: 'suno',
    starterTopic: '여름 드라이브에 어울리는 청량하고 감각적인 신스팝/디스코 댄스 트랙, 경쾌한 베이스라인과 중독성 있는 후렴구',
    description: 'Verse, Chorus, Bridge 구조와 보컬 스타일 지정',
  },

  // 6. 코드 / 개발 (Code)
  {
    id: 'code-ui',
    category: 'code',
    title: 'React 반응형 UI 컴포넌트',
    resultType: '프론트엔드 UI 컴포넌트',
    targetAi: 'cursor',
    starterTopic: 'React, Tailwind CSS, TypeScript를 활용한 반응형 카드 그리드 및 실시간 검색/필터링 UI 컴포넌트',
    description: '타입 안정성, 반응형 레이아웃, 모던 UI 디자인 컴포넌트 설계',
  },
  {
    id: 'code-api',
    category: 'code',
    title: 'Node.js RESTful API 엔드포인트',
    resultType: '백엔드 API 엔드포인트',
    targetAi: 'cursor',
    starterTopic: 'Node.js Express 기반의 JWT 사용자 인증, 입력 유효성 검사 및 정교한 에러 핸들링을 갖춘 REST API',
    description: '견고한 예외 처리와 표준 상태 코드를 준수하는 서버 API',
  },
  {
    id: 'code-func',
    category: 'code',
    title: '고성능 알고리즘 유틸리티 함수',
    resultType: '알고리즘 및 유틸리티 함수',
    targetAi: 'claude',
    starterTopic: '대규모 배열 데이터에서 중복을 제거하고 조건별로 집계하는 시간복잡도 O(N)의 최적화 유틸리티 함수',
    description: '에지 케이스 방어와 성능 최적화가 적용된 순수 함수',
  },
  {
    id: 'code-db',
    category: 'code',
    title: '관계형 데이터베이스 스키마 설계',
    resultType: '데이터베이스 스키마 설계',
    targetAi: 'chatgpt',
    starterTopic: '이커머스 서비스의 사용자, 주문, 결제, 장바구니 테이블 관계를 정규화한 PostgreSQL 스키마 및 인덱스 설계',
    description: '외래 키 제약 조건과 쿼리 성능을 고려한 DB 스키마',
  },

  // 7. 데이터 / 분석 (Data)
  {
    id: 'data-abtest',
    category: 'data',
    title: 'A/B 테스트 분석 및 가설 검증',
    resultType: 'A/B 테스트 분석 및 가설 검증',
    targetAi: 'chatgpt',
    starterTopic: '결제 페이지 버튼 문구 변경에 따른 전환율 개선 A/B 테스트 결과 해석 및 p-value 통계적 유의성 검정',
    description: '가설 설정, 통계 검정, 비즈니스 의사결정 권고안 도출',
  },
  {
    id: 'data-kpi',
    category: 'data',
    title: 'SaaS 비즈니스 KPI 대시보드 설계',
    resultType: 'KPI 대시보드 지표 설계',
    targetAi: 'claude',
    starterTopic: 'B2B SaaS 기업의 MRR, Churn Rate, LTV, CAC 핵심 성과 지표 대시보드 및 알림 임계치 설계',
    description: '경영진과 실무팀을 위한 핵심 지표 트리 구조화',
  },
  {
    id: 'data-retention',
    category: 'data',
    title: '고객 코호트 리텐션 진단',
    resultType: '고객 코호트 분석 및 리텐션 진단',
    targetAi: 'chatgpt',
    starterTopic: '월별 신규 가입 유저의 주차별 리텐션 커브를 분석하고 이탈 주요 요인을 도출하는 진단 리포트',
    description: '코호트 표 해석과 이탈 구간별 맞춤형 활성화 액션 플랜',
  },
  {
    id: 'data-market',
    category: 'data',
    title: '시장 트렌드 데이터 분석 리포트',
    resultType: '시장 점유율 데이터 분석 보고서',
    targetAi: 'auto',
    starterTopic: '국내외 생성형 AI 시장 규모 전망 및 주요 경쟁사 점유율 데이터를 바탕으로 한 종합 분석 보고서',
    description: '시장 기회와 경쟁 우위 전략을 도출하는 거시 데이터 분석',
  },

  // 8. 기타 / 커스텀 (Other)
  {
    id: 'other-brand',
    category: 'other',
    title: '브랜드 네이밍 & 슬로건 10선',
    resultType: '브랜드 네이밍 및 슬로건 도출',
    targetAi: 'chatgpt',
    starterTopic: '친환경 모빌리티 스타트업을 위한 직관적이고 기억하기 쉬운 브랜드 네이밍과 한 줄 슬로건 10선',
    description: '브랜드 철학과 고객 인식을 연결하는 창의적 네이밍',
  },
  {
    id: 'other-interview',
    category: 'other',
    title: '심층 직무 인터뷰 질문지',
    resultType: '인터뷰 질문지 작성',
    targetAi: 'claude',
    starterTopic: '시니어 프로덕트 디자이너 채용을 위한 문제 해결 역량 및 팀 협업 태도 검증 1:1 심층 인터뷰 질문지',
    description: '지원자의 실제 역량과 경험을 입체적으로 평가하는 구조화된 질문지',
  },
  {
    id: 'other-workflow',
    category: 'other',
    title: '노코드 업무 자동화 워크플로',
    resultType: '업무 자동화 워크플로 설계',
    targetAi: 'auto',
    starterTopic: '고객 문의 접수부터 담당자 자동 배정 및 슬랙 알림까지 연결하는 노코드 자동화 워크플로 설계',
    description: '트리거, 액션, 조건 분기 중심의 프로세스 자동화 설계',
  },
  {
    id: 'other-event',
    category: 'other',
    title: '네트워킹 이벤트 타임테이블 기획',
    resultType: '이벤트 기획 및 프로그램 구성',
    targetAi: 'chatgpt',
    starterTopic: '스타트업 창업가들을 위한 3시간짜리 네트워킹 데이 아이스브레이킹 및 패널 토크 프로그램 구성안',
    description: '청중 만족도와 자연스러운 교류를 유도하는 시간대별 프로그램',
  },
];
